# Generated by Django 5.0.4 on 2024-04-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_comment_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book',
            new_name='ebook',
        ),
    ]
