# Generated by Django 5.0.4 on 2024-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0009_alter_comment_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
