# Generated by Django 5.0.4 on 2024-07-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0010_alter_comment_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
