# Generated by Django 5.0.4 on 2024-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='cover',
            field=models.CharField(default='assets/CoverTemplates/template1.png', max_length=2000),
            preserve_default=False,
        ),
    ]
