# Generated by Django 5.0.4 on 2024-06-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Template', '0002_template_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='previewurl',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
