# Generated by Django 4.0.4 on 2024-04-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='categories',
            field=models.ManyToManyField(related_name='bookCategory', to='eBook.category'),
        ),
        migrations.DeleteModel(
            name='eBookCategory',
        ),
    ]
