# Generated by Django 5.0.4 on 2024-04-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('eBook', '0002_ebook_categories_delete_ebookcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
    ]
