# Generated by Django 5.0.4 on 2024-04-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBook', '0003_alter_ebook_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='content',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='cover',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
