# Generated by Django 5.0.4 on 2024-04-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_profile_image'),
        ('eBook', '0004_alter_ebook_content_alter_ebook_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='User.user'),
        ),
    ]
