# Generated by Django 5.0.4 on 2024-04-17 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Template', '0001_initial'),
        ('eBook', '0005_alter_ebook_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='Template.template'),
            preserve_default=False,
        ),
    ]
