# Generated by Django 5.0.4 on 2024-04-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eBook', '0006_ebook_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='template',
        ),
    ]
