# Generated by Django 5.0.4 on 2024-06-12 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBook', '0012_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='template',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
