# Generated by Django 5.0.4 on 2024-06-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBook', '0013_remove_ebook_template_alter_rating_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
