# Generated by Django 4.0.4 on 2024-04-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='querySearch',
            new_name='Search',
        ),
    ]
