# Generated by Django 5.0.4 on 2024-04-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(default='assets/profile.png', max_length=2000),
        ),
    ]
