# Generated by Django 5.0.4 on 2024-04-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='users',
            new_name='users_id',
        ),
    ]
