# Generated by Django 5.0.4 on 2024-04-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_rename_users_userprofile_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='users_id',
            new_name='user',
        ),
    ]
