# Generated by Django 5.0.4 on 2024-05-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(default='https://drive.google.com/thumbnail?id=1cCbs7SU4Ph8j3bnweJsouYqnkOkhlsiH', max_length=2000),
        ),
    ]
