# Generated by Django 5.0.4 on 2024-06-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(default='https://drive.google.com/thumbnail?id=1_122Fgg1wlH6pYvYNFQIPBimWxQwLzD-', max_length=2000),
        ),
    ]
