# Generated by Django 5.0.4 on 2024-06-20 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eBook', '0014_ebook_is_reviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPgae', models.IntegerField(default=1)),
                ('highest_progress', models.IntegerField(default=1)),
                ('totalPages', models.IntegerField(default=0)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookReaded', to='eBook.ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userReader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
