# Generated by Django 5.0.4 on 2024-06-22 05:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReaderAnalysis', '0001_initial'),
        ('eBook', '0014_ebook_is_reviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readeranalysis',
            unique_together={('user', 'ebook')},
        ),
    ]
